# Generated by Django 3.1.3 on 2020-11-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_auto_20201127_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/produto_imagens/%Y/%m/'),
        ),
    ]
