-- Cria Triggers

-- Criando o ambiente

DROP TABLE COPIACOMPARTILHAMENTO; -- DELETA TABELA CASO JÁ EXISTA A TABELA
DROP FUNCTION GERA_LOG(); -- DELETA FUNÇÃO CASO JÁ EXISTA
DROP TRIGGER TR_GERA_LOG ON CONFIGURACAOCOMPARTILHAMENTO; -- DELETA TRIGGER CASO JÁ EXISTA


CREATE LANGUAGE PLPGSQL; --CASO AINDA NÃO EXISTA

-- CRIA UMA CÓPIA DA TABELA COM APENAS OS DADOS DA CONFIGURAÇÃO DO COMPARTILHAMENTO
CREATE TABLE COPIACOMPARTILHAMENTO
	AS SELECT CONF_ID ID, CLIENTE_CLI_ID ID_CLIENTE, CONF_COMP_DADOS DADOS, 
	          CONF_COMP_COMPRAS COMPRAS 
    FROM CONFIGURACAOCOMPARTILHAMENTO;
	
-- INCLUI DUAS COLUNAS PARA VERIFICAR O LOG, CASO SEJA NECESSÁRIO FAZER UMA AUDITORIA
ALTER TABLE COPIACOMPARTILHAMENTO ADD DATAOPERACAO TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL;

CREATE FUNCTION GERA_LOG() RETURNS TRIGGER AS
$$
BEGIN
	INSERT INTO COPIACOMPARTILHAMENTO (ID, ID_CLIENTE, DADOS, COMPRAS, DATAOPERACAO) 
									   VALUES (NOW(), USER, TG_OP);
	RETURN NEW;
END;

$$ LANGUAGE 'PLPGSQL';

CREATE TRIGGER TR_GERA_LOG AFTER INSERT OR UPDATE ON CONFIGURACAOCOMPARTILHAMENTO 

FOR EACH ROW EXECUTE PROCEDURE GERA_LOG();

