CREATE DATABASE PIJava;

USE PIJava;

CREATE TABLE PIUSER (
    USER_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(15) NOT NULL,
    USER_EMAIL VARCHAR(40) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR(15) NOT NULL,
    USER_ADMIN BOOLEAN NOT NULL
);

CREATE TABLE SUPPLIER (
    SUPPLIER_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
    SUPPLIER_CNPJ BIGINT(14) NOT NULL UNIQUE,
    SUPPLIER_NAME VARCHAR(30),
    SUPPLIER_SITE VARCHAR(60),
    SUPPLIER_TYPE VARCHAR(10),
    SUPPLIER_USER_ID INTEGER(10),
    SUPPLIER_ALTER_BY INTEGER(10),
    CONSTRAINT FK_SUPPLIERALTER FOREIGN KEY (SUPPLIER_ALTER_BY) REFERENCES PIUSER (USER_ID),
    CONSTRAINT FK_SUPPLIERUSER FOREIGN KEY (SUPPLIER_USER_ID) REFERENCES PIUSER (USER_ID)
);

CREATE TABLE CLIENT_REGISTER(
CLIENT_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
CLIENT_CPF BIGINT(11) NOT NULL,
CLIENT_NAME VARCHAR(40) NOT NULL,
CLIENT_ZIP_COD VARCHAR(8) NOT NULL,
CLIENT_STREET_NAME VARCHAR(40) NOT NULL,
CLIENT_STREET_NUMBER INTEGER(10) NOT NULL,
CLIENT_STREET_COMPLEMENT VARCHAR(40),
CLIENT_CITY VARCHAR (40) NOT NULL,
CLIENT_STATE VARCHAR(2) NOT NULL,
CLIENT_METER_NUMBER BIGINT(10) UNIQUE NOT NULL,
CLIENT_MEASUREMENT_ORDER VARCHAR(10) NOT NULL,
CLIENT_LIGHT_CLASS VARCHAR(20) NOT NULL,
CLIENT_LIGHT_SUBCLASS VARCHAR(40) NOT NULL,
CLIENT_NORMAL_TAX NUMERIC(15,5) NOT NULL,
CLIENT_TRIBUTE_TAX NUMERIC(15,5),
CLIENT_SUPPLIER_CNPJ BIGINT(14),
CLIENT_USER_ID INTEGER(10),
CLIENT_ALTER_BY INTEGER(10),
CONSTRAINT FK_CLIENTALTER FOREIGN KEY (CLIENT_ALTER_BY) REFERENCES PIUSER (USER_ID),
CONSTRAINT FK_CLIENTUSER FOREIGN KEY (CLIENT_USER_ID) REFERENCES PIUSER (USER_ID),
CONSTRAINT FK_CLIENTSUPPLIER FOREIGN KEY (CLIENT_SUPPLIER_CNPJ) REFERENCES SUPPLIER (SUPPLIER_CNPJ)
);


CREATE TABLE WATER_ACCOUNT (
	ACCOUNT_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NUMBER BIGINT(15) NOT NULL,
    ACCOUNT_DUE_DATE VARCHAR(13) NOT NULL,
    ACCOUNT_PENALTY NUMERIC(15,2),
    ACCOUNT_CONSUMPTION NUMERIC(15,2),
    ACCOUNT_POLLUTION  NUMERIC(15,2),
    ACCOUNT_SEWER NUMERIC(15,2),
    ACCOUNT_WATER NUMERIC(15,2),
    ACCOUNT_PIS INT(2),
    ACCOUNT_OTHERS NUMERIC(15,2),
	ACCOUNT_USER_ID INTEGER (10) NOT NULL,
    ACCOUNT_SUPPLIER_CNPJ BIGINT(14) NOT NULL,
    ACCOUNT_ALTER_BY INTEGER(10) NOT NULL,
    CONSTRAINT FK_WATERALTER FOREIGN KEY (ACCOUNT_ALTER_BY) REFERENCES PIUSER (USER_ID),
    CONSTRAINT FK_WATERCLIENT FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES CLIENT_REGISTER (CLIENT_METER_NUMBER),
    CONSTRAINT FK_WATERUSER FOREIGN KEY (ACCOUNT_USER_ID) REFERENCES PIUSER (USER_ID),
    CONSTRAINT FK_WATERSUPPLIERS FOREIGN KEY (ACCOUNT_SUPPLIER_CNPJ) REFERENCES SUPPLIER (SUPPLIER_CNPJ)
);


CREATE TABLE LIGHT_ACCOUNT(

	LIGHT_ID INTEGER(10) AUTO_INCREMENT PRIMARY KEY,
    LIGHT_IDENT_COD INTEGER(10) NOT NULL,
    LIGHT_METER_NUMBER BIGINT(10) NOT NULL,
    LIGHT_INVOICE VARCHAR(10) NOT NULL,
    LIGHT_CURRENT_DATE VARCHAR(13) NOT NULL,
    LIGHT_DUE_DATE VARCHAR(13) NOT NULL,
    LIGHT_CONSUMPTION_DAYS INTEGER(3) NOT NULL,
    LIGHT_FLAG_TYPE VARCHAR(10) NOT NULL,
    LIGHT_CONSUMPTION_VALUE NUMERIC(15,2) NOT NULL,
    LIGHT_PIS_PERCENTAGE NUMERIC(15,2) NOT NULL,
    LIGHT_COFINS_PERCENTAGE NUMERIC(15,2) NOT NULL,
    LIGHT_ICMS_BASIS NUMERIC(15,2) NOT NULL,
    LIGHT_ICMS_PERCENTAGE NUMERIC(15,2) NOT NULL,
    LIGHT_ICMS_VALUE NUMERIC(15,2) NOT NULL,
    LIGHT_PIS_COFINS_BASIS NUMERIC(15,2) NOT NULL,
    LIGHT_PIS_VALUE NUMERIC(15,2) NOT NULL,
    LIGHT_COFINS_VALUE NUMERIC(15,2) NOT NULL,
    LIGHT_FORFEIT_VALUE NUMERIC(15,2),
    LIGHT_INTEREST_VALUE NUMERIC(15,2),
    LIGHT_OTHER_VALUES NUMERIC(15,2),
    LIGHT_SUPPLY_VALUES NUMERIC(15,2),
    LIGHT_FINANCIAL_ITEMS NUMERIC(15,2),
    LIGHT_AMOUNT NUMERIC(15,2) NOT NULL,
    LIGHT_SUPPLIER_CNPJ BIGINT(14) NOT NULL,
	LIGHT_USER_ID INTEGER(14) NOT NULL,
    LIGHT_ALTER_BY INTEGER(10) NOT NULL,
    CONSTRAINT FK_LIGHTALTER FOREIGN KEY (LIGHT_ALTER_BY) REFERENCES PIUSER (USER_ID),
    CONSTRAINT FK_LIGHTCLIENT FOREIGN KEY (LIGHT_METER_NUMBER) REFERENCES CLIENT_REGISTER (CLIENT_METER_NUMBER),
    CONSTRAINT FK_LIGHTUSER FOREIGN KEY (LIGHT_USER_ID) REFERENCES PIUSER (USER_ID),
    CONSTRAINT FK_LIGHTSUPPLIERS FOREIGN KEY (LIGHT_SUPPLIER_CNPJ) REFERENCES SUPPLIER (SUPPLIER_CNPJ)
   );