/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modeloDao.DaoVeiculo;
import modeloConection.ConexaoBD;
import modeloDao.DaoFuncionario;
import static java.awt.SystemColor.control;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansFuncionario;
import modeloBeans.BeansVeiculo;
import modeloBeans.ModeloTabela;

public class FormVeiculos extends javax.swing.JFrame {

    BeansVeiculo mod = new BeansVeiculo();
    DaoVeiculo dao = new DaoVeiculo();
    ConexaoBD conex = new ConexaoBD();
    int flag=0;
     
    public FormVeiculos() {
        initComponents();
        preenchertabela("select *from veiculos order by placa");
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelVeiculo = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelAno = new javax.swing.JLabel();
        jLabelPlaca1 = new javax.swing.JLabel();
        jLabelChassi1 = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jTextFieldChassi = new javax.swing.JTextField();
        jTextFieldAno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE VEÍCULOS");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Veículos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 450, 30);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair_32.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setToolTipText("Voltar a Tela Anterior");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(680, 10, 100, 40);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_24.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(200, 250, 120, 30);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("Cadastrar Novo Veículo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(30, 30, 110, 33);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar Dados Atuais");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(30, 80, 110, 33);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar Ação Atual");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(30, 130, 110, 33);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setToolTipText("Editar Dados");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(30, 180, 110, 33);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remover.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir Informações");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(30, 230, 110, 30);

        jLabelVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVeiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVeiculo.setText("MARCA DO VEÍCULO");
        getContentPane().add(jLabelVeiculo);
        jLabelVeiculo.setBounds(170, 130, 110, 20);

        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelID.setText("ID");
        getContentPane().add(jLabelID);
        jLabelID.setBounds(250, 60, 34, 40);

        jLabelAno.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAno.setText("ANO VEÍCULO");
        getContentPane().add(jLabelAno);
        jLabelAno.setBounds(440, 180, 90, 20);

        jLabelPlaca1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlaca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlaca1.setText("PLACA");
        getContentPane().add(jLabelPlaca1);
        jLabelPlaca1.setBounds(170, 180, 90, 20);

        jLabelChassi1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChassi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChassi1.setText("CHASSI");
        getContentPane().add(jLabelChassi1);
        jLabelChassi1.setBounds(430, 130, 90, 20);

        jtID.setEnabled(false);
        getContentPane().add(jtID);
        jtID.setBounds(300, 60, 120, 30);

        jTextFieldPlaca.setEnabled(false);
        getContentPane().add(jTextFieldPlaca);
        jTextFieldPlaca.setBounds(300, 180, 120, 30);

        jTextFieldMarca.setEnabled(false);
        getContentPane().add(jTextFieldMarca);
        jTextFieldMarca.setBounds(300, 130, 120, 30);
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(330, 250, 160, 30);

        jTextFieldChassi.setEnabled(false);
        getContentPane().add(jTextFieldChassi);
        jTextFieldChassi.setBounds(540, 130, 120, 30);

        jTextFieldAno.setEnabled(false);
        getContentPane().add(jTextFieldAno);
        jTextFieldAno.setBounds(540, 180, 120, 30);

        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVeiculo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 290, 510, 230);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wall-wallpaper-concrete-colored-painted-textured-concept.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 790, 530);

        setSize(new java.awt.Dimension(809, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
       flag = 2;
       jTextFieldMarca.setEnabled(true);
       jTextFieldAno.setEnabled(true);
       jTextFieldChassi.setEnabled(true);
       jTextFieldPlaca.setEnabled(true);
       jButtonCancelar.setEnabled(true);
       jButtonSalvar.setEnabled(true);
       jTextFieldPesquisa.setEnabled(false);
       jButtonPesquisar.setEnabled(false);
       jButtonPesquisar.setEnabled(false);
       jTextFieldPesquisa.setText("");
       jtID.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipalAdmin tela = new TelaPrincipalAdmin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
      if(flag == 2){         
      
      mod.setMarca_veiculo(jTextFieldMarca.getText());
      mod.setPlaca_veiculo(jTextFieldPlaca.getText());
      mod.setAno_veiculo(jTextFieldAno.getText());
      mod.setChassi(jTextFieldChassi.getText());
      dao.Salvar(mod);
      jTextFieldAno.setEnabled(false);
      jTextFieldChassi.setEnabled(false);
      jTextFieldMarca.setEnabled(false);
      jTextFieldPlaca.setEnabled(false);
      jButtonSalvar.setEnabled(false);
      jButtonCancelar.setEnabled(false);
      jTextFieldPesquisa.setEnabled(true);
      jButtonPesquisar.setEnabled(true);
      jTextFieldMarca.setText("");
      jTextFieldAno.setText("");
      jTextFieldPlaca.setText("");
      jTextFieldChassi.setText("");
      preenchertabela("select *from veiculos order by marca_veiculo");
      
      }else{
      mod.setCod(Integer.valueOf(jtID.getText()));
      mod.setMarca_veiculo(jTextFieldMarca.getText());
      mod.setPlaca_veiculo(jTextFieldPlaca.getText());
      mod.setAno_veiculo(jTextFieldAno.getText());
      mod.setChassi(jTextFieldChassi.getText());
      dao.Editar(mod);
      
      jTextFieldMarca.setText("");
      jTextFieldAno.setText("");
      jTextFieldPlaca.setText("");
      jTextFieldChassi.setText("");
      jTextFieldAno.setEnabled(false);
      jTextFieldChassi.setEnabled(false);
      jTextFieldMarca.setEnabled(false);
      jTextFieldPlaca.setEnabled(false);
      jButtonSalvar.setEnabled(false);
      jButtonCancelar.setEnabled(false);
      jButtonExcluir.setEnabled(false);
      jButtonEditar.setEnabled(false);
      preenchertabela("select *from veiculos order by marca_veiculo");

}
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jTextFieldAno.setEnabled(false);
        jTextFieldChassi.setEnabled(false);
        jTextFieldMarca.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jButtonNovo.setEnabled(true);
        jTextFieldMarca.setText("");
        jTextFieldAno.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldChassi.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 3;
        jTableVeiculo.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jTextFieldMarca.setEnabled(true);
        jTextFieldAno.setEnabled(true);
        jTextFieldPlaca.setEnabled(true);
        jTextFieldChassi.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir?");
        if(resposta ==JOptionPane.YES_OPTION){
        mod.setCod(Integer.parseInt(jtID.getText()));
        dao.Excluir(mod);
        
        jTextFieldMarca.setText("");
        jTextFieldAno.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldChassi.setText("");
        
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jTextFieldAno.setEnabled(false);
        jTextFieldChassi.setEnabled(false);
        jTextFieldMarca.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        preenchertabela("select *from veiculos order by marca_veiculo");
        }
         
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
       flag = 3;
        mod.setveiculopesquisa(jTextFieldPesquisa.getText());
        BeansVeiculo model = dao.buscaVeiculo(mod);

        jtID.setText(String.valueOf(model.getCod()));
        jTextFieldMarca.setText(model.getMarca_veiculo());
        jTextFieldPlaca.setText(model.getPlaca_veiculo());
        jTextFieldAno.setText(model.getAno_veiculo());
        jTextFieldChassi.setText(model.getChassi());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTableVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculoMouseClicked
       String nome_funcionario = ""+jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(),1 );
        
       conex.conexao();
       
       conex.executaSql("select *from veiculos where marca_veiculo='"+nome_funcionario+"'");
        try {
            conex.rs.first();
        jtID.setText(String.valueOf(conex.rs.getInt("cod_id")));
        jTextFieldMarca.setText(conex.rs.getString("marca_veiculo"));
        jTextFieldPlaca.setText(conex.rs.getString("placa"));
        jTextFieldAno.setText(String.valueOf(conex.rs.getInt("ano_Veiculo")));
        jTextFieldChassi.setText(conex.rs.getString("numero_chassi"));

            
        } catch (SQLException ex) { 
            JOptionPane.showMessageDialog(null,"Erro ao selecionar Dados:\n"+ex.getMessage());
        }

       conex.desconecta();
       
       jButtonEditar.setEnabled(true);
       jButtonExcluir.setEnabled(true);
       jButtonNovo.setEnabled(false);
       jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jTableVeiculoMouseClicked
    public void preenchertabela(String sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String []{
        "ID","Marca","Placa","Ano","Chassi"};
        conex.conexao();
        
        conex.executaSql(sql);
        try {
            conex.rs.first();
            do{
            dados.add(new Object[]{conex.rs.getInt("cod_id"),conex.rs.getString("marca_veiculo"),conex.rs.getString("placa"),conex.rs.getInt("ano_veiculo"),conex.rs.getString("numero_chassi")});
            
             }while(conex.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Preencher\n:"+ex.getMessage());
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableVeiculo.setModel(modelo);
        
        jTableVeiculo.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableVeiculo.getColumnModel().getColumn(0).setResizable(false);
           
        jTableVeiculo.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableVeiculo.getColumnModel().getColumn(1).setResizable(false);
           
        jTableVeiculo.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableVeiculo.getColumnModel().getColumn(2).setResizable(false);
           
        jTableVeiculo.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableVeiculo.getColumnModel().getColumn(3).setResizable(false);
           
        jTableVeiculo.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableVeiculo.getColumnModel().getColumn(4).setResizable(false);
   
        jTableVeiculo.getTableHeader().setReorderingAllowed(false);
        jTableVeiculo.setAutoResizeMode(jTableVeiculo.AUTO_RESIZE_OFF);
        jTableVeiculo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
}
            
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelChassi1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPlaca1;
    private javax.swing.JLabel jLabelVeiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jtID;
    // End of variables declaration//GEN-END:variables
}
