/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modeloConection.ConexaoBD;

public class TelaPrincipalAdmin extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD(); //estanciei a conexão na classe atual
    
    
    public TelaPrincipalAdmin() {
        
        conecta.conexao(); // método que chama a conexão
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadFuncuncionarios = new javax.swing.JButton();
        jButtonCadVeiculos = new javax.swing.JButton();
        jButtonCadEntrega = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU ADMINISTRADOR");
        getContentPane().setLayout(null);

        jButtonCadFuncuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funcionario.png"))); // NOI18N
        jButtonCadFuncuncionarios.setText("Funcionários");
        jButtonCadFuncuncionarios.setToolTipText("Cadastrar Funcionário");
        jButtonCadFuncuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadFuncuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadFuncuncionarios);
        jButtonCadFuncuncionarios.setBounds(40, 460, 150, 50);

        jButtonCadVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caminhoes.png"))); // NOI18N
        jButtonCadVeiculos.setText("Veículos");
        jButtonCadVeiculos.setToolTipText("Cadastrar Veículo");
        jButtonCadVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadVeiculosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadVeiculos);
        jButtonCadVeiculos.setBounds(460, 460, 150, 50);

        jButtonCadEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/entrega.png"))); // NOI18N
        jButtonCadEntrega.setText("Entregas");
        jButtonCadEntrega.setToolTipText("Cadastrar Viagem");
        jButtonCadEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEntregaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadEntrega);
        jButtonCadEntrega.setBounds(250, 460, 150, 50);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(520, 10, 100, 41);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TELA DE CADASTRO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 0, 390, 80);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundoprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 630, 540);

        setSize(new java.awt.Dimension(645, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        conecta.desconecta();
        
        System.exit(0);
        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadFuncuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadFuncuncionariosActionPerformed
        FormFuncionario tela = new FormFuncionario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadFuncuncionariosActionPerformed

    private void jButtonCadVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadVeiculosActionPerformed
        FormVeiculos tela = new FormVeiculos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCadVeiculosActionPerformed

    private void jButtonCadEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEntregaActionPerformed
       FormAgenda tel = new FormAgenda();
       tel.setVisible(true);
       dispose();
               
    }//GEN-LAST:event_jButtonCadEntregaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadEntrega;
    private javax.swing.JButton jButtonCadFuncuncionarios;
    private javax.swing.JButton jButtonCadVeiculos;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFundoPrincipal;
    // End of variables declaration//GEN-END:variables
}
