# Generated by Django 2.2 on 2020-06-19 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0003_auto_20200618_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=20, verbose_name='Habilidades')),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Hard Skills'), (2, 'Soft Skills')], verbose_name='Tipo de Habilidade')),
                ('user_add', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_habilidade_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_habilidade_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='vagas.Habilidade'),
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
