# Generated by Django 2.2 on 2020-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_auto_20200626_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Beneficio')),
            ],
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='beneficios',
        ),
        migrations.AlterField(
            model_name='vaga',
            name='categoria',
            field=models.SmallIntegerField(choices=[(1, 'Engenharia Civil'), (2, 'Marketing'), (3, 'Tecnologia (TI)')]),
        ),
    ]
