# Generated by Django 2.2 on 2020-07-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0010_auto_20200709_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='date_upd',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='user_add',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='user_upd',
        ),
    ]
