/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConection.ConexaoBD;
import modeloDao.DaoFuncionario;
import modeloBeans.BeansFuncionario;
import modeloBeans.ModeloTabela;

/**
 *
 * @author deliro
 */
public class FormFuncionario extends javax.swing.JFrame {
    
    BeansFuncionario mod = new BeansFuncionario();
    ConexaoBD conex = new ConexaoBD();
    DaoFuncionario control = new DaoFuncionario();
    int flag = 0;
    
    public FormFuncionario() {
        initComponents();
        preencherTabela("select *from funcionarios order by nome_funcionario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNomeFunc = new javax.swing.JLabel();
        jLabelSenhaFunc = new javax.swing.JLabel();
        jLabelCpfFunc = new javax.swing.JLabel();
        jLabelRGFunc = new javax.swing.JLabel();
        jLabelCNHFunc = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jComboBoxCNH = new javax.swing.JComboBox<>();
        jTextFieldNome = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtCOD = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelFundoFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO DE FUNCIONÁRIOS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNomeFunc.setText("Nome");

        jLabelSenhaFunc.setText("Senha");

        jLabelCpfFunc.setText("CPF");

        jLabelRGFunc.setText("RG");

        jLabelCNHFunc.setText("CNH");

        jFormattedTextFieldCPF.setEnabled(false);

        jComboBoxCNH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "D", "E" }));
        jComboBoxCNH.setToolTipText("Selecione sua Modalidade");
        jComboBoxCNH.setAlignmentX(1.0F);
        jComboBoxCNH.setEnabled(false);

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jPasswordFieldSenha.setEnabled(false);

        jFormattedTextFieldRG.setEnabled(false);
        jFormattedTextFieldRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldRGActionPerformed(evt);
            }
        });

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remover.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionarios);

        jButtonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.setToolTipText("Pesquisar Funcionário");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jtCOD.setEnabled(false);
        jtCOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCODActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelCpfFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelNomeFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRGFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldCPF)
                                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCNHFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNomeFunc)))
                            .addComponent(jButtonNovo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonSalvar)
                                .addComponent(jLabelCpfFunc))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSenhaFunc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRGFunc)
                            .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCNHFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButtonCancelar)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 815, 494);

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Painel de Cadastro de Funcionários");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(193, 13, 440, 32);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair_32.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setToolTipText("Voltar para a Tela Anterior");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(710, 10, 111, 33);

        jLabelFundoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wall-wallpaper-concrete-colored-painted-textured-concept.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoFuncionario);
        jLabelFundoFuncionario.setBounds(0, 0, 830, 560);

        setSize(new java.awt.Dimension(848, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
     TelaPrincipalAdmin tela = new TelaPrincipalAdmin();
     tela.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jComboBoxCNH.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jtCOD.setText("");
        jButtonCancelar.setEnabled(true);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jPasswordFieldSenha.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jComboBoxCNH.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jPasswordFieldSenha.setText("");
        jFormattedTextFieldRG.setText("");
        jtCOD.setText("");
        jTextFieldPesquisa.setText("");
        preencherTabela("select *from funcionarios order by nome_funcionario");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
      if(jTextFieldNome.getText().isEmpty()){
      JOptionPane.showMessageDialog(null,"Preencha o Campo");
      jTextFieldNome.requestFocus();
      
      }else if(jFormattedTextFieldCPF.getText().isEmpty()){jFormattedTextFieldCPF.requestFocus();
            JOptionPane.showMessageDialog(null,"Preencha o Campo");
            
      }else{
      }
        {
       if (flag == 2){
        mod.setNome(jTextFieldNome.getText());
        mod.setSenha(jPasswordFieldSenha.getText());
        mod.setCpf(Integer.parseInt(jFormattedTextFieldCPF.getText()));
        mod.setRg(Integer.parseInt(jFormattedTextFieldRG.getText()));
        mod.setCnh((String) jComboBoxCNH.getSelectedItem());
        control.Salvar(mod);
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jPasswordFieldSenha.setText("");
        jFormattedTextFieldRG.setText("");
        jComboBoxCNH.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jPasswordFieldSenha.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jComboBoxCNH.setEnabled(false);
        jTextFieldPesquisa.setText("");
        preencherTabela("select *from funcionarios order by nome_funcionario");
       }else{
        mod.setCodigo((Integer.parseInt(jtCOD.getText())));
        mod.setCpf(Integer.parseInt(jFormattedTextFieldCPF.getText()));
        mod.setNome(jTextFieldNome.getText());
        mod.setSenha(jPasswordFieldSenha.getText());
        mod.setRg(Integer.parseInt(jFormattedTextFieldRG.getText()));
        mod.setCnh((String)jComboBoxCNH.getSelectedItem());
        control.Editar(mod);
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jPasswordFieldSenha.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jComboBoxCNH.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jTextFieldPesquisa.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jPasswordFieldSenha.setText("");
        jFormattedTextFieldRG.setText("");
        jtCOD.setText("");
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        }
       preencherTabela("select *from funcionarios order by nome_funcionario");
      }   
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
       flag = 3;
       mod.setPesquisa(jTextFieldPesquisa.getText());
       BeansFuncionario model = control.buscaFuncionario(mod);
       jtCOD.setText(String.valueOf(model.getCodigo()));
       jTextFieldNome.setText(model.getNome());
       jPasswordFieldSenha.setText(model.getSenha());
       jFormattedTextFieldCPF.setText(String.valueOf(model.getCpf()));
       jFormattedTextFieldRG.setText(String.valueOf(model.getRg()));
       jComboBoxCNH.setSelectedItem(model.getCnh());
       preencherTabela("select *from funcionarios where nome_funcionario like'%"+mod.getPesquisa()+"%'");
       jButtonAlterar.setEnabled(false);
       jButtonExcluir.setEnabled(false);
      
       
      
       
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 3;
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jComboBoxCNH.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        preencherTabela("select *from funcionarios order by nome_funcionario");
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jtCODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCODActionPerformed

    private void jFormattedTextFieldRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldRGActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
      int resposta = 0;
      
      resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente Excluir?");
      
      if(resposta == JOptionPane.YES_OPTION){     
          mod.setCodigo(Integer.parseInt(jtCOD.getText()));
          control.Excluir(mod);
        jTextFieldPesquisa.setText("");
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jPasswordFieldSenha.setText("");
        jFormattedTextFieldRG.setText("");
        jtCOD.setText("");
        jButtonNovo.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jPasswordFieldSenha.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jComboBoxCNH.setEnabled(false);
        preencherTabela("select *from funcionarios order by nome_funcionario");
      }      
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked
        String nome_funcionario = ""+jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select *from funcionarios where nome_funcionario='"+nome_funcionario+"'");
        try {
            conex.rs.first();
            jtCOD.setText(String.valueOf(conex.rs.getInt("cod_funcionario")));
            jTextFieldNome.setText(conex.rs.getString("nome_funcionario"));
            jPasswordFieldSenha.setText(conex.rs.getString("senha_funcionario"));
            jFormattedTextFieldCPF.setText(String.valueOf(conex.rs.getInt("cpf_funcionario")));
            jFormattedTextFieldRG.setText(String.valueOf(conex.rs.getInt("rg_funcionario")));
            jComboBoxCNH.setSelectedItem(conex.rs.getString("cnh_funcionario"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao selecionar Dados:\n"+ex.getMessage());
        }
        conex.desconecta();
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
    }//GEN-LAST:event_formWindowActivated

        public void preencherTabela(String Sql){
    
        ArrayList dados = new ArrayList();
        String[] colunas = new String []{
        "ID","Nome","CPF","Senha","RG","CNH"};
        conex.conexao();
        conex.executaSql(Sql);
        
        
        
        try{
            conex.rs.first();
            do{ 
                dados.add(new Object[]{conex.rs.getInt("cod_funcionario"),conex.rs.getString("nome_funcionario"),conex.rs.getString("senha_funcionario"),conex.rs.getInt("cpf_funcionario"),conex.rs.getInt("rg_funcionario"),conex.rs.getString("cnh_funcionario")});
                
                }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Busque por outro Funcionário");
            
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableFuncionarios.setModel(modelo);
        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
        jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
        jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(95);
        jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
        jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(95);
        jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);
        jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(95);
        jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);
        jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(95);
        jTableFuncionarios.getColumnModel().getColumn(5).setResizable(false);
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
        jTableFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
   
} 

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxCNH;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCNHFunc;
    private javax.swing.JLabel jLabelCpfFunc;
    private javax.swing.JLabel jLabelFundoFuncionario;
    private javax.swing.JLabel jLabelNomeFunc;
    private javax.swing.JLabel jLabelRGFunc;
    private javax.swing.JLabel jLabelSenhaFunc;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jtCOD;
    // End of variables declaration//GEN-END:variables
}
