/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansAgenda;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoAgenda;

/**
 *
 * @author deliro
 */
public class FormAgenda extends javax.swing.JFrame {
    ConexaoBD conex = new ConexaoBD();
    BeansAgenda agenda = new BeansAgenda();
    /**
     * Creates new form CriaEntrega
     */
    public FormAgenda() {
        initComponents();
        preencherveiculos();
        preenchertabela("select *from funcionarios order by nome_funcionario");
        
    }
    
    public void preencherveiculos(){
    
    conex.conexao();
    conex.executaSql("select *from veiculos order by marca_veiculo");   
        try {
            conex.rs.first();
            jComboBoxVeiculo.removeAllItems();
            do{
                jComboBoxVeiculo.addItem(conex.rs.getString("marca_veiculo"));
                }while(conex.rs.next());
        } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao Preencher Veículo:\n"+e.getMessage());
            
        }
    
    
    conex.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFuncionario = new javax.swing.JLabel();
        jTextFieldFuncionario = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jLabelVeiculo = new javax.swing.JLabel();
        jComboBoxVeiculo = new javax.swing.JComboBox<>();
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxUF = new javax.swing.JComboBox<>();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereço = new javax.swing.JTextField();
        jLabelCarga = new javax.swing.JLabel();
        jTextFieldCarga = new javax.swing.JTextField();
        jButtonFinalizarAgendamento = new javax.swing.JButton();
        jButtonCancelarAgendamento = new javax.swing.JButton();
        jLabelOBS = new javax.swing.JLabel();
        jTextFieldObservaçao = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelFundoCriaEntrega = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRIAR ENTREGA");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabelFuncionario.setText("Funcionario:");
        jPanel1.add(jLabelFuncionario);
        jLabelFuncionario.setBounds(10, 20, 80, 14);

        jTextFieldFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFuncionario);
        jTextFieldFuncionario.setBounds(90, 20, 110, 20);

        jLabelData.setText("Data Prevista:");
        jPanel1.add(jLabelData);
        jLabelData.setBounds(400, 20, 90, 20);

        jTableFuncionarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionarios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 60, 507, 220);

        jLabelVeiculo.setText("Veiculo:");
        jPanel1.add(jLabelVeiculo);
        jLabelVeiculo.setBounds(10, 315, 60, 14);

        jPanel1.add(jComboBoxVeiculo);
        jComboBoxVeiculo.setBounds(90, 310, 150, 20);

        jLabelEstado.setText("Estado:");
        jPanel1.add(jLabelEstado);
        jLabelEstado.setBounds(390, 310, 70, 20);

        jComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        jComboBoxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUFActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxUF);
        jComboBoxUF.setBounds(440, 310, 150, 20);

        jLabelEndereco.setText("Endereço:");
        jPanel1.add(jLabelEndereco);
        jLabelEndereco.setBounds(10, 353, 70, 14);
        jPanel1.add(jTextFieldEndereço);
        jTextFieldEndereço.setBounds(100, 350, 140, 20);

        jLabelCarga.setText("Carga:");
        jPanel1.add(jLabelCarga);
        jLabelCarga.setBounds(10, 391, 60, 14);
        jPanel1.add(jTextFieldCarga);
        jTextFieldCarga.setBounds(100, 390, 140, 20);

        jButtonFinalizarAgendamento.setText("Finalizar Agendamento");
        jButtonFinalizarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarAgendamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFinalizarAgendamento);
        jButtonFinalizarAgendamento.setBounds(410, 370, 173, 23);

        jButtonCancelarAgendamento.setText("Cancelar Agendamento");
        jPanel1.add(jButtonCancelarAgendamento);
        jButtonCancelarAgendamento.setBounds(410, 420, 173, 23);

        jLabelOBS.setText("Observação:");
        jPanel1.add(jLabelOBS);
        jLabelOBS.setBounds(10, 430, 90, 14);
        jPanel1.add(jTextFieldObservaçao);
        jTextFieldObservaçao.setBounds(100, 430, 140, 20);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar);
        jButtonBuscar.setBounds(220, 20, 90, 23);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(500, 20, 150, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 60, 660, 480);

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Criar Entrega");
        jLabelTitulo.setToolTipText("");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(170, 10, 350, 40);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sair_32.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setToolTipText("Voltar Tela Anterior");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(590, 10, 100, 40);

        jLabelFundoCriaEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wall-wallpaper-concrete-colored-painted-textured-concept.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoCriaEntrega);
        jLabelFundoCriaEntrega.setBounds(0, 0, 710, 560);

        setSize(new java.awt.Dimension(726, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUFActionPerformed
public void preenchertabela(String sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String []{
        "ID","Nome","Senha","CPF","RG", "CNH"};
        conex.conexao();
        
        conex.executaSql(sql);
        try {
            conex.rs.first();
            do{
            dados.add(new Object[]{conex.rs.getInt("cod_funcionario"),conex.rs.getString("nome_funcionario"),conex.rs.getString("senha_funcionario"),conex.rs.getInt("cpf_funcionario"),conex.rs.getInt("rg_funcionario"),conex.rs.getString("cnh_funcionario")});
            
             }while(conex.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Preencher Tabela\n"+ex.getMessage());
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableFuncionarios.setModel(modelo);
        
        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
           
        jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
           
        jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
           
        jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);
           
        jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);
           
        jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(50);
        jTableFuncionarios.getColumnModel().getColumn(5).setResizable(false);
        
  
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
        jTableFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
}
    
    
    
    
    
    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
       TelaPrincipalAdmin tela = new TelaPrincipalAdmin();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        preenchertabela("select cod_funcionario,nome_funcionario,senha_funcionario,cpf_funcionario,rg_funcionario,cnh_funcionario from funcionarios where nome_funcionario like'%"+jTextFieldFuncionario.getText()+"%'");
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked
   String nome_funcionario = ""+jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(),1 );
       conex.conexao();
       
       conex.executaSql("select *from funcionarios where nome_funcionario='"+nome_funcionario+"'");
        try {
            conex.rs.first();
        jTextFieldFuncionario.setText(conex.rs.getString("nome_funcionario"));

        } catch (SQLException ex) {
           //  Logger.getLogger(CriarEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
        conex.desconecta();
    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    private void jButtonFinalizarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarAgendamentoActionPerformed
       
       agenda.setNomeFuncionario(jTextFieldFuncionario.getText());
       agenda.setNomeVeiculo((String) jComboBoxVeiculo.getSelectedItem());
       agenda.setCarga(jTextFieldCarga.getText());
       agenda.setEstado((String) jComboBoxUF.getSelectedItem());
       agenda.setEndereço(jTextFieldEndereço.getText());
       agenda.setObs(jTextFieldObservaçao.getText());
       agenda.setData(jDateChooser1.getDate());
       DaoAgenda dao = new DaoAgenda();
       dao.Salvar(agenda);
       
       
    }//GEN-LAST:event_jButtonFinalizarAgendamentoActionPerformed

    private void jTextFieldFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelarAgendamento;
    private javax.swing.JButton jButtonFinalizarAgendamento;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxUF;
    private javax.swing.JComboBox<String> jComboBoxVeiculo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabelCarga;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelFundoCriaEntrega;
    private javax.swing.JLabel jLabelOBS;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldCarga;
    private javax.swing.JTextField jTextFieldEndereço;
    private javax.swing.JTextField jTextFieldFuncionario;
    private javax.swing.JTextField jTextFieldObservaçao;
    // End of variables declaration//GEN-END:variables
}
