//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIFATECForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_UF_2020
    {
        public int cd_uf { get; set; }
        public string nm_uf { get; set; }
        public string sigla_uf { get; set; }
        public string nm_regiao { get; set; }
    }
}
