# Generated by Django 3.0.6 on 2020-05-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Pessoa',
            fields=[
                ('pes_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('pes_nome', models.CharField(max_length=90, verbose_name='Nome')),
                ('pes_contato', models.BigIntegerField(verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Projeto',
            fields=[
                ('prj_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('prj_nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('prj_escopo', models.CharField(max_length=119, verbose_name='Escopo')),
                ('prj_datainicio', models.DateField(verbose_name='Data Inicio')),
                ('prj_prazoentrega', models.DateField(verbose_name='Prazo de Entrega')),
                ('prj_color', models.CharField(default='', max_length=60, verbose_name='Cor')),
            ],
        ),
        migrations.CreateModel(
            name='tbTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Tarefa',
            fields=[
                ('trf_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('trf_name', models.CharField(default='', max_length=120, verbose_name='nome')),
                ('trf_datainicial', models.DateField(verbose_name='Data Inicial')),
                ('trf_datafinal', models.DateField(null=True, verbose_name='Data Final')),
                ('trf_prazo', models.DateField(verbose_name='Prazo')),
                ('trf_interdependencia', models.IntegerField(default=0, null=True, verbose_name='Interdenpencia')),
                ('trf_entregavel', models.BooleanField(default=False, verbose_name='Entregavel')),
                ('fk_prj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Dev_Trf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_pes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_Pessoa')),
                ('fk_trf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_Tarefa')),
            ],
            options={
                'unique_together': {('fk_pes_id', 'fk_trf_id')},
            },
        ),
    ]
