# Generated by Django 3.0.6 on 2020-05-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_tarefa',
            name='trf_color',
            field=models.CharField(default='', max_length=16, verbose_name='cor'),
        ),
    ]
