# Generated by Django 3.0.6 on 2020-06-03 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0002_tb_tarefa_trf_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_dev_trf',
            name='fk_prj_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_Projeto'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tb_dev_trf',
            unique_together={('fk_pes_id', 'fk_trf_id', 'fk_prj_id')},
        ),
    ]
