# Generated by Django 3.0.7 on 2020-06-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0006_auto_20200618_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_tarefa',
            name='trf_progresso',
            field=models.IntegerField(default=0, null=True, verbose_name='progresso'),
        ),
    ]
