# Generated by Django 3.0.7 on 2020-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0007_tb_tarefa_trf_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_projeto',
            name='prj_cost',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=19, null=True, verbose_name='Custo'),
        ),
        migrations.AddField(
            model_name='tb_projeto',
            name='prj_hrs_dev',
            field=models.IntegerField(default=0, null=True, verbose_name='Horas Desenvolvimento'),
        ),
        migrations.AddField(
            model_name='tb_projeto',
            name='prj_progresso',
            field=models.IntegerField(default=0, null=True, verbose_name='Progresso'),
        ),
    ]
