# Generated by Django 3.0.7 on 2020-06-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0007_tb_tarefa_trf_progresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_habilidades',
            fields=[
                ('hab_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('hab_nome', models.CharField(max_length=120, verbose_name='habilidade')),
            ],
        ),
        migrations.CreateModel(
            name='tb_hab_pes',
            fields=[
                ('pes_trf_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('fk_hab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_habilidades')),
                ('fk_pes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_Pessoa')),
            ],
        ),
    ]
