# Generated by Django 3.0.7 on 2020-06-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0008_tb_hab_pes_tb_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_pessoa',
            name='pes_faltas',
            field=models.IntegerField(default=0, null=True, verbose_name='Faltas'),
        ),
        migrations.AddField(
            model_name='tb_pessoa',
            name='pes_hrs_disponivel',
            field=models.IntegerField(default=0, null=True, verbose_name='Hrs Disponiveis'),
        ),
        migrations.AddField(
            model_name='tb_pessoa',
            name='pes_salario',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=19, verbose_name='Salario'),
        ),
    ]
