# Generated by Django 3.0.7 on 2020-06-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0009_auto_20200620_1940'),
        ('gantt', '0008_auto_20200620_1753'),
    ]

    operations = [
    ]
