# Generated by Django 3.0.7 on 2020-06-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0010_merge_20200621_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_hab_pes',
            name='pes_hab_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tb_habilidades',
            name='hab_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterUniqueTogether(
            name='tb_hab_pes',
            unique_together={('fk_pes_id', 'fk_hab_id')},
        ),
        migrations.RemoveField(
            model_name='tb_hab_pes',
            name='pes_trf_id',
        ),
    ]
