# Generated by Django 3.0.7 on 2020-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0010_merge_20200621_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_pessoa',
            name='pes_hrs_disponivel_ano',
            field=models.IntegerField(default=0, null=True, verbose_name='Hrs Disponiveis por Ano'),
        ),
    ]
