# Generated by Django 3.0.7 on 2020-06-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0011_auto_20200626_0139'),
        ('gantt', '0011_tb_pessoa_pes_hrs_disponivel_ano'),
    ]

    operations = [
    ]
