const DEVICE = {
  FETCH: 'DEVICE_FETCH',
  FETCH_ERROR: 'DEVICE_FETCH_ERROR',
  FETCH_SUCCESS: 'DEVICE_FETCH_SUCCESS'
};

const ACCOUNT = {
  FETCH: 'ACCOUNT_FETCH',
  FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
  FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
  FETCH_LOGOUT_SUCCESS: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
  FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
};

const ACCOUNT_DEVICES = {
  FETCH: 'ACCOUNT_DEVICE_FETCH',
  FETCH_ERROR: 'ACCOUNT_DEVICE_FETCH_ERROR',
  FETCH_SUCCESS: 'ACCOUNT_DEVICE_FETCH_SUCCESS'
};

const ACCOUNT_INFO = {
  FETCH: 'ACCOUNT_INFO_FETCH',
  FETCH_ERROR: 'ACCOUNT_INFO_FETCH_ERROR',
  FETCH_SUCCESS: 'ACCOUNT_INFO_FETCH_SUCCESS'
};

export {
  DEVICE,
  ACCOUNT,
  ACCOUNT_DEVICES,
  ACCOUNT_INFO
};