# Generated by Django 2.2 on 2020-06-10 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=20)),
                ('nivel', models.SmallIntegerField(choices=[(1, 'Avançado'), (2, 'Intermediário'), (3, 'Básico')])),
                ('user_add', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_competencia_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_competencia_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('id_vaga', models.CharField(max_length=20, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')])),
                ('nome_vaga', models.CharField(max_length=100, verbose_name='Denominação da Vaga')),
                ('qtd_vaga', models.SmallIntegerField(verbose_name='Quantidade de vagas')),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Engenharia Civil'), (2, 'Martketing'), (3, 'Tecnologia (TI)')])),
                ('cidade', models.SmallIntegerField(choices=[(1, 'Acre (AC)'), (2, 'Alagoas (AL)'), (3, 'Amapá (AP)'), (4, 'Amazonas (AM)'), (5, 'Bahia (BA)'), (6, 'Ceará (CE)'), (7, 'Distrito Federal (DF)'), (8, 'Espírito Santo (ES)'), (9, 'Goiás (GO)'), (10, 'Maranhão (MA)'), (11, 'Mato Grosso (MT)'), (12, 'Mato Grosso do Sul (MS)'), (13, 'Minas Gerais (MG)'), (14, 'Pará (PA)'), (15, 'Paraíba (PB)'), (16, 'Paraná (PR)'), (17, 'Pernambuco (PE)'), (18, 'Piauí (PI)'), (19, 'Rio de Janeiro (RJ)'), (20, 'Rio Grande do Norte (RN)'), (21, 'Rio Grande do Sul (RS)'), (22, 'Rondônia (RO)'), (23, 'Roraima (RR)'), (24, 'Santa Catarina (SC)'), (25, 'São Paulo (SP)'), (26, 'Sergipe (SE)'), (27, 'Tocantins (TO)')], verbose_name='Estado em que a vaga se encontra')),
                ('horario_trab', models.SmallIntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite'), (4, '1.º Turno'), (5, '2.º Turno'), (6, '3.º Turno')], null=True, verbose_name='Período')),
                ('beneficios', models.SmallIntegerField(blank=True, choices=[(1, 'Previdência Privada'), (2, 'Convênio Médico'), (3, 'Vale Alimentação'), (4, 'Vale Transporte')], null=True)),
                ('descricao', models.TextField(verbose_name='Descrição da Vaga')),
                ('exp_requerida', models.TextField(blank=True, null=True, verbose_name='Experiências necessárias')),
                ('competencia', models.ManyToManyField(to='vagas.Competencia')),
                ('user_add', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_vaga_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_vaga_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
