# Generated by Django 2.2 on 2020-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_auto_20200619_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Habilidade'),
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Hard Skills'), (2, 'Soft Skills')], verbose_name='Tipo da Habilidade'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='qtd_vaga',
            field=models.PositiveSmallIntegerField(verbose_name='Quantidade de vagas'),
        ),
    ]
