# Generated by Django 2.2 on 2020-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_auto_20200709_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF'),
        ),
    ]
