# Generated by Django 2.2 on 2020-07-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_auto_20200709_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='date_upd',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='user_add',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='user_upd',
        ),
    ]
