"""empty message

Revision ID: 1ed13064487e
Revises: 9fce92585974
Create Date: 2021-05-15 07:19:16.293297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ed13064487e'
down_revision = '9fce92585974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers_products', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('customers_products', 'inserted_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True)
    op.alter_column('customers_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True)
    op.drop_constraint('customers_products_product_id_fkey', 'customers_products', type_='foreignkey')
    op.drop_constraint('customers_products_customer_id_fkey', 'customers_products', type_='foreignkey')
    op.create_foreign_key(None, 'customers_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'customers_products', 'customers', ['customer_id'], ['id'])
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'customers_products', type_='foreignkey')
    op.drop_constraint(None, 'customers_products', type_='foreignkey')
    op.create_foreign_key('customers_products_customer_id_fkey', 'customers_products', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('customers_products_product_id_fkey', 'customers_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('customers_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False)
    op.alter_column('customers_products', 'inserted_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False)
    op.alter_column('customers_products', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
