"""empty message

Revision ID: 4c0bf13867cf
Revises: 1fe7957ad0f3
Create Date: 2021-05-12 19:51:14.184558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c0bf13867cf'
down_revision = '1fe7957ad0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('products')
    op.add_column('users', sa.Column('customer_state', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('customer_city', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('customer_age', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('customer_avg_income', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('customer_products_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('transactions_total_limit', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('transactions_category', sa.String(length=30), nullable=True))
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('username', table_name='users')
    op.drop_index('username_2', table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'number')
    op.drop_column('users', 'username')
    op.drop_column('users', 'street')
    op.drop_column('users', 'city')
    op.drop_column('users', 'contato')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contato', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('users', sa.Column('city', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('users', sa.Column('street', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('users', sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=30), nullable=True))
    op.create_index('username_2', 'users', ['username'], unique=False)
    op.create_index('username', 'users', ['username'], unique=False)
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('users', 'transactions_category')
    op.drop_column('users', 'transactions_total_limit')
    op.drop_column('users', 'customer_products_active')
    op.drop_column('users', 'customer_avg_income')
    op.drop_column('users', 'customer_age')
    op.drop_column('users', 'customer_city')
    op.drop_column('users', 'customer_state')
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('subtitle', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('img', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('prices', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('units', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_posted', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='order_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
