"""empty message

Revision ID: 974108a9aca7
Revises: 54ba313331b1
Create Date: 2021-06-05 15:00:56.111702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974108a9aca7'
down_revision = '54ba313331b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csvdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csvdata')
    # ### end Alembic commands ###
