"""empty message

Revision ID: f30062764f4e
Revises: 46b3390adcfa
Create Date: 2021-05-12 22:14:06.528543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f30062764f4e'
down_revision = '46b3390adcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transactions_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transactions_category', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
