"""empty message

Revision ID: 288a5936fd3b
Revises: 84c684fe8fbc
Create Date: 2021-05-19 08:47:28.171244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288a5936fd3b'
down_revision = '84c684fe8fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('save_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'save_data', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'save_data', type_='foreignkey')
    op.drop_column('save_data', 'user_id')
    # ### end Alembic commands ###
