"""empty message

Revision ID: 9c115618878f
Revises: 1c53df166182
Create Date: 2021-05-12 19:57:37.609970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c115618878f'
down_revision = '1c53df166182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transactions_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transactions_category', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
