# Generated by Django 3.0.5 on 2021-03-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Radar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conteudo',
        ),
    ]
