/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Regiao;
import dao.RegiaoDAO;

/**
 *
 * @author Leandro
 */
public class Região extends javax.swing.JFrame {

    /**
     * Creates new form Região
     */
    public Região() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ConsultaRegiaoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaRegiao = new javax.swing.JTable();
        pesquisarButton = new javax.swing.JButton();
        pesquisarTextF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        InsercaoRegiaoPanel = new javax.swing.JPanel();
        insereEstadoTextF = new javax.swing.JTextField();
        insereSiglaTextF = new javax.swing.JTextField();
        insereRegiaoTextF = new javax.swing.JTextField();
        insereHoraExtraTextF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        errorMessageLabel = new javax.swing.JLabel();
        AtualizacaoRegiaoPanel = new javax.swing.JPanel();
        atualizaEstadoTextF = new javax.swing.JTextField();
        atualizaSiglaTextF = new javax.swing.JTextField();
        atualizaRegiaoTextF = new javax.swing.JTextField();
        atualizaValorHoraExtraTextF = new javax.swing.JTextField();
        atualizaRegiaoButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        errorMessageLabel2 = new javax.swing.JLabel();
        atualizaRegiaoTextF2 = new javax.swing.JTextField();
        atualizaValorHoraExtraTextF2 = new javax.swing.JTextField();
        atualizaEstadoTextF2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ExclusaoRegiaoPanel = new javax.swing.JPanel();
        excluirEstadoTextF = new javax.swing.JTextField();
        excluirRegiaoTextF = new javax.swing.JTextField();
        excluirValorHoraExtraTextF = new javax.swing.JTextField();
        excluirRegiaoButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        errorMessageLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelaRegiao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"São Paulo", "SP", "Sudeste", "200"}
            },
            new String [] {
                "Estado", "Sigla", "Região", "Valor Hora Extra"
            }
        ));
        jScrollPane1.setViewportView(TabelaRegiao);

        pesquisarButton.setText("Pesquisar");
        pesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Estado:");

        javax.swing.GroupLayout ConsultaRegiaoPanelLayout = new javax.swing.GroupLayout(ConsultaRegiaoPanel);
        ConsultaRegiaoPanel.setLayout(ConsultaRegiaoPanelLayout);
        ConsultaRegiaoPanelLayout.setHorizontalGroup(
            ConsultaRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaRegiaoPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(ConsultaRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaRegiaoPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaRegiaoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisarTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        ConsultaRegiaoPanelLayout.setVerticalGroup(
            ConsultaRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultaRegiaoPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(ConsultaRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsultaRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pesquisarTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", ConsultaRegiaoPanel);

        insereEstadoTextF.setToolTipText("Estado");

        insereSiglaTextF.setToolTipText("Sigla");

        insereRegiaoTextF.setToolTipText("Regiao");

        insereHoraExtraTextF.setToolTipText("Valor Hora Extra");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Estado:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Sigla:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Região:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Valor da Hora Extra:");

        errorMessageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout InsercaoRegiaoPanelLayout = new javax.swing.GroupLayout(InsercaoRegiaoPanel);
        InsercaoRegiaoPanel.setLayout(InsercaoRegiaoPanelLayout);
        InsercaoRegiaoPanelLayout.setHorizontalGroup(
            InsercaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsercaoRegiaoPanelLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(InsercaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(InsercaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insereEstadoTextF)
                        .addComponent(insereSiglaTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(insereRegiaoTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(insereHoraExtraTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        InsercaoRegiaoPanelLayout.setVerticalGroup(
            InsercaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsercaoRegiaoPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insereEstadoTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insereSiglaTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insereRegiaoTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insereHoraExtraTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inserção", InsercaoRegiaoPanel);

        atualizaRegiaoButton.setText("Atualizar");
        atualizaRegiaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaRegiaoButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Estado:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Sigla:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Região:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Valor da Hora Extra:");

        errorMessageLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Valor da Hora Extra:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Região:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Estado:");

        javax.swing.GroupLayout AtualizacaoRegiaoPanelLayout = new javax.swing.GroupLayout(AtualizacaoRegiaoPanel);
        AtualizacaoRegiaoPanel.setLayout(AtualizacaoRegiaoPanelLayout);
        AtualizacaoRegiaoPanelLayout.setHorizontalGroup(
            AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtualizacaoRegiaoPanelLayout.createSequentialGroup()
                .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtualizacaoRegiaoPanelLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizaRegiaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorMessageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AtualizacaoRegiaoPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(atualizaEstadoTextF)
                                .addComponent(atualizaRegiaoTextF)
                                .addComponent(atualizaValorHoraExtraTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(atualizaValorHoraExtraTextF2)
                                .addComponent(jLabel7)
                                .addComponent(atualizaSiglaTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(atualizaRegiaoTextF2)
                                .addComponent(atualizaEstadoTextF2))
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        AtualizacaoRegiaoPanelLayout.setVerticalGroup(
            AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtualizacaoRegiaoPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atualizaEstadoTextF2)
                    .addComponent(atualizaEstadoTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtualizacaoRegiaoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizaRegiaoTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AtualizacaoRegiaoPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizaSiglaTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(3, 3, 3)
                .addGroup(AtualizacaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtualizacaoRegiaoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizaValorHoraExtraTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atualizaRegiaoTextF2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizaValorHoraExtraTextF2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(atualizaRegiaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMessageLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Atualização", AtualizacaoRegiaoPanel);

        excluirRegiaoButton.setText("Exlcuir");
        excluirRegiaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirRegiaoButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Estado:");

        jLabel11.setText("Região:");

        jLabel12.setText("Valor da Hora Extra:");

        errorMessageLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout ExclusaoRegiaoPanelLayout = new javax.swing.GroupLayout(ExclusaoRegiaoPanel);
        ExclusaoRegiaoPanel.setLayout(ExclusaoRegiaoPanelLayout);
        ExclusaoRegiaoPanelLayout.setHorizontalGroup(
            ExclusaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExclusaoRegiaoPanelLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(ExclusaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMessageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addGroup(ExclusaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(excluirRegiaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirEstadoTextF)
                        .addComponent(excluirRegiaoTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addComponent(excluirValorHoraExtraTextF, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        ExclusaoRegiaoPanelLayout.setVerticalGroup(
            ExclusaoRegiaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExclusaoRegiaoPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirEstadoTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirRegiaoTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirValorHoraExtraTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(excluirRegiaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errorMessageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exclusão", ExclusaoRegiaoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarButtonActionPerformed
        try {
            Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/itruck","postgres","camilafatec");
            String querry = "select * from regiao";
            
            //verifica se o Text Field não está vazio e adiciona a condição de pesquisa à querry
            if(!pesquisarTextF.getText().equals(""))
                querry = querry + " where estado LIKE ? ";
            //prepara a querry para ser executada no postgree
            PreparedStatement statement = connection.prepareStatement(querry);
            //verifica se o Text Field não está vazio para colocar o input na condição de pesquisa
            if(!pesquisarTextF.getText().equals(""))
                statement.setString(1, "%"+pesquisarTextF.getText()+"%");
            //pega u retorno da execução da queery e armazena num ResultSet
            ResultSet rs = statement.executeQuery();            
            DefaultTableModel model = (DefaultTableModel) TabelaRegiao.getModel();
            model.setNumRows(0);
            //é usado um loop para armazenar os campos do ResultSet dentro de uma lista para a mesma ser uma row na table disposta no programa
            while(rs.next()){
                
                String[] linha = {rs.getString("estado"),
                    rs.getString("sigla"),rs.getString("reg"),
                    rs.getString("valor_hora_extra")};
                model.addRow(linha);
            }
            
            statement.close();
            connection.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_pesquisarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Regiao regiao = new Regiao();
        
        regiao.setEstado(insereEstadoTextF.getText());
        regiao.setSigla(insereSiglaTextF.getText());
        regiao.setRegiao(insereRegiaoTextF.getText());
        regiao.setValorHoraExtra(insereHoraExtraTextF.getText());
        
        if (insereEstadoTextF.getText().isEmpty() || insereSiglaTextF.getText().isEmpty() || insereRegiaoTextF.getText().isEmpty() || insereHoraExtraTextF.getText().isEmpty()){
            errorMessageLabel.setText("Todos os campos devem ser preenchidos!");
        }
        else{
            RegiaoDAO regiaoDAO = new RegiaoDAO();
            
            regiaoDAO.insere(regiao);
            
            errorMessageLabel.setText("Região inserida no banco de dados com sucesso!");
            
            insereEstadoTextF.setText("");
            insereSiglaTextF.setText("");
            insereRegiaoTextF.setText("");
            insereHoraExtraTextF.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atualizaRegiaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaRegiaoButtonActionPerformed
        try{
            if (insereEstadoTextF.getText().isEmpty() || insereSiglaTextF.getText().isEmpty() || insereRegiaoTextF.getText().isEmpty() || insereHoraExtraTextF.getText().isEmpty()){
            errorMessageLabel.setText("Todos os campos devem ser preenchidos!");
            }
            else{
                Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/itruck","postgres","camilafatec");
                
                String querry = "update regiao set estado=?,sigla=?,reg=?,valor_hora_extra=? where estado=? and reg=? and valor_hora_extra=? ";
                
                PreparedStatement statement = connection.prepareStatement(querry);
                
                statement.setString(1, this.atualizaEstadoTextF2.getText());
                statement.setString(2, this.atualizaSiglaTextF.getText());
                statement.setString(3, this.atualizaRegiaoTextF2.getText());
                statement.setString(4, this.atualizaValorHoraExtraTextF2.getText());
                statement.setString(5, this.atualizaEstadoTextF.getText());
                statement.setString(6, this.atualizaRegiaoTextF.getText());
                statement.setString(7, this.atualizaValorHoraExtraTextF.getText());
                
                statement.execute();
                connection.close();
                
                errorMessageLabel2.setText("Funcionário atualizado com sucesso!");
                atualizaEstadoTextF.setText("");
                atualizaSiglaTextF.setText("");
                atualizaRegiaoTextF.setText("");
                atualizaValorHoraExtraTextF.setText("");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_atualizaRegiaoButtonActionPerformed

    private void excluirRegiaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirRegiaoButtonActionPerformed
        try{
            if (insereEstadoTextF.getText().isEmpty() || insereSiglaTextF.getText().isEmpty() || insereRegiaoTextF.getText().isEmpty() || insereHoraExtraTextF.getText().isEmpty()){
            errorMessageLabel.setText("Todos os campos devem ser preenchidos!");
            }
            else{
                Connection connection =  DriverManager.getConnection("jdbc:postgresql://localhost:5432/itruck","postgres","camilafatec");  
                String sql = "delete from regiao where estado = ? and reg = ? and valor_hora_extra = ?";
                PreparedStatement statement = connection.prepareStatement(sql);
                
                statement.setString(1, this.excluirEstadoTextF.getText());
                statement.setString(2, this.excluirRegiaoTextF.getText());
                statement.setString(3, this.excluirValorHoraExtraTextF.getText());
                
                statement.execute();
                statement.close();
                connection.close();
                
                errorMessageLabel3.setText("Funcionário excluído com Sucesso!");
                excluirEstadoTextF.setText("");
                excluirRegiaoTextF.setText("");
                excluirValorHoraExtraTextF.setText("");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_excluirRegiaoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Região.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Região.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Região.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Região.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Região().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AtualizacaoRegiaoPanel;
    private javax.swing.JPanel ConsultaRegiaoPanel;
    private javax.swing.JPanel ExclusaoRegiaoPanel;
    private javax.swing.JPanel InsercaoRegiaoPanel;
    private javax.swing.JTable TabelaRegiao;
    private javax.swing.JTextField atualizaEstadoTextF;
    private javax.swing.JTextField atualizaEstadoTextF2;
    private javax.swing.JButton atualizaRegiaoButton;
    private javax.swing.JTextField atualizaRegiaoTextF;
    private javax.swing.JTextField atualizaRegiaoTextF2;
    private javax.swing.JTextField atualizaSiglaTextF;
    private javax.swing.JTextField atualizaValorHoraExtraTextF;
    private javax.swing.JTextField atualizaValorHoraExtraTextF2;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel errorMessageLabel2;
    private javax.swing.JLabel errorMessageLabel3;
    private javax.swing.JTextField excluirEstadoTextF;
    private javax.swing.JButton excluirRegiaoButton;
    private javax.swing.JTextField excluirRegiaoTextF;
    private javax.swing.JTextField excluirValorHoraExtraTextF;
    private javax.swing.JTextField insereEstadoTextF;
    private javax.swing.JTextField insereHoraExtraTextF;
    private javax.swing.JTextField insereRegiaoTextF;
    private javax.swing.JTextField insereSiglaTextF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton pesquisarButton;
    private javax.swing.JTextField pesquisarTextF;
    // End of variables declaration//GEN-END:variables
}
