/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Leandro
 */
public class VehicleManagement extends javax.swing.JFrame {

    /**
     * Creates new form VehicleManagement
     */
    public VehicleManagement() {
        initComponents();
        this.setTitle("Gerenciamento de Veículo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectVehicleButton = new javax.swing.JButton();
        InsertVehicleButton = new javax.swing.JButton();
        UpdateVehicleButton = new javax.swing.JButton();
        DeleteVehicleButton = new javax.swing.JButton();
        VehicleManagementTitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectVehicleButton.setText("Consultar");
        SelectVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectVehicleButtonActionPerformed(evt);
            }
        });

        InsertVehicleButton.setText("Cadastrar");
        InsertVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertVehicleButtonActionPerformed(evt);
            }
        });

        UpdateVehicleButton.setText("Atualizar");
        UpdateVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateVehicleButtonActionPerformed(evt);
            }
        });

        DeleteVehicleButton.setText("Excluir");
        DeleteVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteVehicleButtonActionPerformed(evt);
            }
        });

        VehicleManagementTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        VehicleManagementTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VehicleManagementTitleLabel.setText("Veículos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VehicleManagementTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelectVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsertVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(UpdateVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(DeleteVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VehicleManagementTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InsertVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectVehicleButtonActionPerformed
        new consultaveiculoGUI().setVisible(true);
    }//GEN-LAST:event_SelectVehicleButtonActionPerformed

    private void InsertVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertVehicleButtonActionPerformed
        new veiculoGUI().setVisible(true);
    }//GEN-LAST:event_InsertVehicleButtonActionPerformed

    private void UpdateVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateVehicleButtonActionPerformed
        new atualizarveiculoGUI().setVisible(true);
    }//GEN-LAST:event_UpdateVehicleButtonActionPerformed

    private void DeleteVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteVehicleButtonActionPerformed
        new excluirveiculoGUI().setVisible(true);
    }//GEN-LAST:event_DeleteVehicleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteVehicleButton;
    private javax.swing.JButton InsertVehicleButton;
    private javax.swing.JButton SelectVehicleButton;
    private javax.swing.JButton UpdateVehicleButton;
    private javax.swing.JLabel VehicleManagementTitleLabel;
    // End of variables declaration//GEN-END:variables
}
