package com.tecsus.ddc.bill.energy;

public enum Classe {
    RESIDENCIAL,
    RURAL,
    COOPERATIVA_DE_ELETRIFICACAO_RURAL,
    SERVICOS_PUBLICOS_DE_IRRIGACAO,
    DEMAIS_CLASSES,
    ILUMINACAO_PUBLICA,
    INDUSTRIAL
}
